[package]
name = "_prql_library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate_type = ["staticlib", "cdylib"]
doctest = false
test = false

[dependencies]
prql-compiler = "0.4.0"
libc = "0.2"
serde_json = "1.0"

